### PR TITLE
Unification localisations into one file with change log file

### PR DESCRIPTION
**Pull request by mikekubn**
Added `team.json` with localisations and added change log.

- Will must do:
- [x] add localizations
- [x] set version of json

This is only kick off for versioning json file with team. Let's go to discuss what will be best approach.
Related with [PR-171](https://github.com/cesko-digital/movapp/pull/171)

### CODE REVIEW

**Comment by mikekubn** [comment]
- Do we want to use change log outside .json file?
- Do we want that .json contains version?
- Do we want to use version inside name of .json file `team.v1.json`?

**Comment by pionl** [comment]
Thank you for the changes 🚀

🥇 Im ok with proposed file structure.

🤔 I would not add version to the file - another thing we need to take care.

🙏 I would only use main version within file name to prevent client crashes on breaking changes.

🤔 Also changelog should not be a part of cdn data folder (but in root). 

🥹 And also i think we do not need separate changelog file 👍

**Comment by mikekubn** [comment]
> I would not add version to the file - another thing we need to take care.

@pionl thanks for fast answer! 🚀
Your points make sense! So the best solution will be to use `team.v1.json` and if someone edits this file, they will have to create a new one with the new version so as not to break the current version that will be used by our frontends.

**Comment by pionl** [comment]
> they will have to create a new one with the new version so as not to break the current version that will be used by our frontends.

Only if the changes alters the json structure in breaking changes (if we add new property it should not break the app right?). If the changes contains only new additions (new name, new section) then we do not need to update the clients so no need of new version 🚀

Could you update 📖 README.md with proposed "release" strategy of team.json?

Thank you! 🙌

**Review by pionl — APPROVED** [review]

**Comment by met** [comment]
@mikekubn I made small update to people names in team.json (add 2 news people and one changed girls name), please update it in your PR too. https://github.com/cesko-digital/movapp-data/pull/33

**Comment by mikekubn** [comment]
> > they will have to create a new one with the new version so as not to break the current version that will be used by our frontends.
> 
> Only if the changes alters the json structure in breaking changes (if we add new property it should not break the app right?). If the changes contains only new additions (new name, new section) then we do not need to update the clients so no need of new version 🚀
> 
> Could you update 📖 README.md with proposed "release" strategy of team.json?
> 
> Thank you! 🙌

@pionl 
> If we add new property it should not break the app right?
- It should be okay, only schema validator will be broke and developer has to fix schema.

**Comment by pionl** [comment]
@mikekubn did you want to delete the branch?

**Pull request merged**
